config/routes.rb
Tictac::Application.routes.draw do

  get "games/index"

  get "games/search"

  get "games/show"

  get "games/make_move"

  resources :games


  root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :a1, :a2, :a3, :b1, :b2, :b3, :c1, :c2, :c3, :name, :player_id, :owner_id

  belongs_to :owner, class_name: "Player"



end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :game_id, :move_id, :name

  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def create
    @game = Game.new(params[:game])
    @game.save

    redirect_to :back
  end

  def search
    #find correct session
    @current = Game.find_by_name(params[:search])
    @player = Player.find_by_name(params[:player_name])
  end

  def make_move
    @game = Game.find_by_name(params[:name])
    params[:loc].parameterize.underscore.to_sym
    @game.update_attributes(params[:loc].parameterize.underscore.to_sym  => params[:a1])

    #check_win(@game)

    redirect_to :back
  end

  def check_win(game)
    if [@game.a1, @game.a2, @game.a3].all? {|x|x == x}
      flash[:notice] = "You won"
    elsif [@game.b1, @game.b2, @game.b3].all? {|x|x == x}
      flash[:notice] = "You won"
    elsif [@game.c1, @game.c2, @game.c3].all? {|x|x == x}
      flash[:notice] = "You won"
    end
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/games_helper.rb
module GamesHelper

  #toggle between correct user, to make move
  def selection(loc,spot)
    if loc.nil?
      link_to "[   ]", games_make_move_path(a1: "x", name: @current.name, loc: spot)
    else
      loc
    end
  end

  def o_selection(loc,spot)
    if loc.nil?
      link_to "[   ]", games_make_move_path(a1: "o", name: @current.name, loc: spot)
    else
      loc
    end
  end

  # Websockets by Faye, wasn't able to completely implement
  def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block) }
    uri = URI.parse("http://localhost:9292/faye")
    NET::HTTP.post_form(uri, :message => message.to_json)
  end
end

app/views/games/index.html.erb
<div class="container">
  <h1>Hello Tic-Tac-Toe</h1>

  <div class="row">
    <div class="col-md-4">

    <%= form_tag games_search_path, method: 'get' do %>

      <p>
        Name
        <%= text_field_tag :player_name, params[:player_name] %>
      </p>

      <p>
        Game
        <%= text_field_tag :search, params[:search] %>
      </p>

      <p>
        <%= submit_tag ("Refresh") %>
      </p>
    <% end %>
  </div>

  <div class="col-md-6">
    <table class="table">
      <tr>
        <th></th>
        <th>A</th>
        <th>B</th>
        <th>C</th>
      </tr>
        <th>1<%#= link_to "X", games_path(:game => {a1: "x", name: ""}),id: "name_save"%> </th>
        <!-- Should be able to create game via POST method and Javascript, didn't get it correctly working -->
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
      </tr>

      <tr>
        <th>2</th>
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
      </tr>

      <tr>
        <th>3</th>
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
        <th><%= link_to "X", games_path(:game => {a1: "x", name: "fo"}),id: "name_save"%> </th>
      </tr>
    </table>

  </div>

  </div> <!-- /Row -->














</div> <!-- /Container -->

app/views/games/search.html.erb
<div class="container">
  <h1>Hello Tic-Tac-Toe</h1>
  <h3><%= @current.name %></h3>
  Your <%= @player.name %>

  <div class="row">
    <div class="col-md-4">

    <%= form_tag games_search_path, method: 'get' do %>

      <p>
        Name
        <%= text_field_tag :player_name %>
      </p>

      <p>
        Game
        <%= text_field_tag :search, params[:search] %>
      </p>

      <p>
        <%= submit_tag ("Refresh") %>
      </p>
    <% end %>
  </div>

  <div class="col-md-6">
    <table class="table">
      <tr>
        <th></th>
        <th>A</th>
        <th>B</th>
        <th>C</th>
      </tr>

      <tr>
        <th>1</th>
        <!-- Toggle between users, because on owner of game -->
        <th><%= @current.owner_id == @player.id ? selection(@current.a1, "a1") : o_selection(@current.a1, "a1")  %></th>
        <th><%= @current.owner_id == @player.id ? selection(@current.a2, "a2") : o_selection(@current.a2, "a2")  %></th>
        <th><%= @current.owner_id == @player.id ? selection(@current.a3, "a3") : o_selection(@current.a3, "a3") %></th>
      </tr>

      <tr>
        <th>2</th>
        <th><%= @current.owner_id == @player.id ? selection(@current.b1, "b1") : o_selection(@current.b1, "b1") %></th>
        <th><%= @current.owner_id == @player.id ? selection(@current.b2, "b2") : o_selection(@current.b2, "b2") %></th>
        <th><%= @current.owner_id == @player.id ? selection(@current.b2, "b3") : o_selection(@current.b3, "b3") %></th>
      </tr>

      <tr>
        <th>3</th>
        <th><%= @current.owner_id == @player.id ? selection(@current.c1, "c1") : o_selection(@current.c1, "c1") %></th>
        <th><%= @current.owner_id == @player.id ? selection(@current.c2, "c2") : o_selection(@current.c2, "c2") %></th>
        <th><%= @current.owner_id == @player.id ? selection(@current.c3, "c3") : o_selection(@current.c3, "c3") %></th>
      </tr>
    </table>

  </div>

  </div> <!-- /Row -->














</div> <!-- /Container -->

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tictac</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" ,"http://localhost:9292/faye.js"%>

  <!-- Bootstrap -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>